-- liquibase formatted sql
--changeset underfit:2
INSERT INTO public.users (name, login, password, role, email, birthday, start_work, work_number) VALUES ('Сидоров Иван Иванович', 'admin1', '$2a$10$JQzWq4XKvUGd7e5uJTHmoeFkRB.WlNnv.xlHuhYpDRv0jbU0bm8e.', 1, 'admin1@gmail.com', '1998-06-16', '2020-07-12', 1);
INSERT INTO public.users (name, login, password, role, email, birthday, start_work, work_number) VALUES ('Иванов Иван Иванович', 'user1', '$2a$10$4QTKDRPDtv38IgTEbBNuT.kw9NxZCpkW5.j.IFXCIqpgLwi.nfeEK', 0, 'user1@gmail.com', '1998-03-12', '2022-03-12', 1);
INSERT INTO public.users (name, login, password, role, email, birthday, start_work, work_number) VALUES ('Иванов Иван Иванович', 'user2', '$2a$10$TjNUgFuOuTrYO9MtiNGdN.Q./lwy8HqoTegGOaQZPqo.9CShOF.i.', 0, 'user2@gmail.com', '1996-05-23', '2021-06-14', 1);

INSERT INTO public.ticket (color, date_withdrawal, reason_withdrawal, user_id) VALUES ('Желтый', '2024-05-07', 'Не справился', 3);
INSERT INTO public.ticket (color, date_withdrawal, reason_withdrawal, user_id) VALUES ('Красный', '2024-05-03', 'Неудача', 2);

INSERT INTO public.test (test_name, description) VALUES ('Оценка склонности к риску, RSK', 'Оцените степень своей готовности совершить действия, о которых вас спрашивают.');

INSERT INTO public.question (question_text, test_id) VALUES ('Превысили бы вы установленную скорость, чтобы быстрее оказать необходимую медицинскую помощь тяжелобольному человеку?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Стали бы вы на пути убегающего опасного взломщика?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Согласились бы вы ради хорошего заработка участвовать в опасной и длительной экспедиции?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы ехать на подножке товарного вагона при скорости более 100 км/ч?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Можете ли вы на другой день после бессонной ночи нормально работать?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Стали бы вы первым переходить вброд очень холодную реку?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Одолжили бы вы другу большую сумму денег, будучи не совсем уверенным, что он сможет их вам вернуть?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Вошли бы вы вместе с укротителем в клетку со львами при его заверении, что это безопасно?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы за большое денежное вознаграждение перейти с завязанными глазами оживленный уличный перекресток?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы при необходимости проехать без билета от Санкт-Петербурга до Москвы?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы прыгнуть с 10-метровой высоты на тент пожарной команды?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы спрыгнуть с подножки товарного вагона, движущегося со скоростью 50 км/ч?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы под руководством извне залезть на высокую фабричную трубу?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы, имея билеты, но без денег и продуктов, доехать от Москвы до Хабаровска?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы после 10 рюмок водки вычислять проценты?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы совершить прыжок с парашютом?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы после нескольких стаканов пива ехать на велосипеде?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы без тренировки управлять парусной лодкой?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Рискнули бы вы схватить за уздечку бегущую лошадь?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы после нескольких предварительных объяснений управлять вертолетом?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Взялись бы вы за опасную работу, если бы за нее хорошо платили?', 1);
INSERT INTO public.question (question_text, test_id) VALUES (' Могли бы вы отправиться в автомобильное путешествие, если бы за рулем сидел ваш знакомый, который совсем недавно был в тяжелом дорожном происшествии?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы в виде исключения вместе с семью другими людьми подняться в лифте, рассчитанном только на шесть человек?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы по указанию начальника взяться за высоковольтный провод, если бы он заверил вас, что провод обесточен?', 1);
INSERT INTO public.question (question_text, test_id) VALUES ('Могли бы вы согласиться на опасную для жизни операцию, если есть шанс избавиться от затяжной болезни с постельным режимом?', 1);

INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 1);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 1);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 1);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 1);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 1);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 2);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 2);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 2);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 2);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 2);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 3);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 3);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 3);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 3);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 3);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 4);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 4);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 4);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 4);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 4);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 5);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 5);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 5);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 5);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 5);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 6);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 6);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 6);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 6);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 6);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 7);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 7);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 7);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 7);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 7);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 8);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 8);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 8);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 8);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 8);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 9);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 9);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 9);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 9);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 9);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 10);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 10);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 10);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 10);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 10);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 11);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 11);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 11);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 11);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 11);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 12);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 12);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 12);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 12);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 12);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 13);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 13);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 13);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 13);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 13);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 14);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 14);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 14);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 14);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 14);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 15);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 15);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 15);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 15);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 15);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 16);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 16);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 16);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 16);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 16);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 17);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 17);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 17);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 17);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 17);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 18);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 18);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 18);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 18);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 18);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 19);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 19);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 19);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 19);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 19);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 20);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 20);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 20);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 20);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 20);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 21);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 21);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 21);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 21);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 21);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 22);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 22);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 22);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 22);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 22);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 23);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 23);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 23);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 23);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 23);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 24);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 24);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 24);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 24);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 24);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно да', 2, 25);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее да, чем нет', 1, 25);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Ни да, ни нет, нечто среднее', 0, 25);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Скорее нет, чем да', -1, 25);
INSERT INTO public.option (option_text, score, question_id) VALUES ('Однозначно нет', -2, 25);

INSERT INTO public.result (score, accept_result, test_id, user_id) VALUES (39, true, 1, 2);
INSERT INTO public.result (score, accept_result, test_id, user_id) VALUES (29, false, 1, 3);
INSERT INTO public.result (score, accept_result, test_id, user_id) VALUES (-30, null, 1, 2);

INSERT INTO public.answer (result_id, option_id) VALUES (1, 1);
INSERT INTO public.answer (result_id, option_id) VALUES (1, 6);

INSERT INTO public.assessment (assessment_name, min_score, max_score, result_description, test_id) VALUES ('Выраженная склонность к рискованному поведению', 20, 50, 'Высокая готовность к риску сопровождается низкой мотивацией к избеганию неудач (защитой). Готовность к риску достоверно связана прямо пропорционально с числом допущенных ошибок. Исследования дали также следующие результаты: - с возрастом готовность к риску падает; - у более опытных работников готовность к риску ниже, чем у неопытных; - у женщин готовность к риску реализуется при более определенных условиях, чем у мужчин; - у военных командиров и руководителей предприятий готовность к риску выше, чем у студентов; - с ростом отверженности личности, в ситуации внутреннего конфликта растет готовность к риску; - в условиях группы готовность к риску проявляется сильней, чем при действиях в одиночку, и зависит от групповых ожиданий.', 1);
INSERT INTO public.assessment (assessment_name, min_score, max_score, result_description, test_id) VALUES ('Умеренная склонность к риску', 11, 19, 'Высокая готовность к риску сопровождается низкой мотивацией к избеганию неудач (защитой). Готовность к риску достоверно связана прямо пропорционально с числом допущенных ошибок. Исследования дали также следующие результаты: - с возрастом готовность к риску падает; - у более опытных работников готовность к риску ниже, чем у неопытных; - у женщин готовность к риску реализуется при более определенных условиях, чем у мужчин; - у военных командиров и руководителей предприятий готовность к риску выше, чем у студентов; - с ростом отверженности личности, в ситуации внутреннего конфликта растет готовность к риску; - в условиях группы готовность к риску проявляется сильней, чем при действиях в одиночку, и зависит от групповых ожиданий.', 1);
INSERT INTO public.assessment (assessment_name, min_score, max_score, result_description, test_id) VALUES ('Среднее значение', -10, 10, 'Высокая готовность к риску сопровождается низкой мотивацией к избеганию неудач (защитой). Готовность к риску достоверно связана прямо пропорционально с числом допущенных ошибок. Исследования дали также следующие результаты: - с возрастом готовность к риску падает; - у более опытных работников готовность к риску ниже, чем у неопытных; - у женщин готовность к риску реализуется при более определенных условиях, чем у мужчин; - у военных командиров и руководителей предприятий готовность к риску выше, чем у студентов; - с ростом отверженности личности, в ситуации внутреннего конфликта растет готовность к риску; - в условиях группы готовность к риску проявляется сильней, чем при действиях в одиночку, и зависит от групповых ожиданий.', 1);
INSERT INTO public.assessment (assessment_name, min_score, max_score, result_description, test_id) VALUES ('Умеренная склонность к осторожному поведению', -29, -11, 'Высокая готовность к риску сопровождается низкой мотивацией к избеганию неудач (защитой). Готовность к риску достоверно связана прямо пропорционально с числом допущенных ошибок. Исследования дали также следующие результаты: - с возрастом готовность к риску падает; - у более опытных работников готовность к риску ниже, чем у неопытных; - у женщин готовность к риску реализуется при более определенных условиях, чем у мужчин; - у военных командиров и руководителей предприятий готовность к риску выше, чем у студентов; - с ростом отверженности личности, в ситуации внутреннего конфликта растет готовность к риску; - в условиях группы готовность к риску проявляется сильней, чем при действиях в одиночку, и зависит от групповых ожиданий.', 1);
INSERT INTO public.assessment (assessment_name, min_score, max_score, result_description, test_id) VALUES ('Выраженная склонность к осторожному поведению', -50, -30, 'Высокая готовность к риску сопровождается низкой мотивацией к избеганию неудач (защитой). Готовность к риску достоверно связана прямо пропорционально с числом допущенных ошибок. Исследования дали также следующие результаты: - с возрастом готовность к риску падает; - у более опытных работников готовность к риску ниже, чем у неопытных; - у женщин готовность к риску реализуется при более определенных условиях, чем у мужчин; - у военных командиров и руководителей предприятий готовность к риску выше, чем у студентов; - с ростом отверженности личности, в ситуации внутреннего конфликта растет готовность к риску; - в условиях группы готовность к риску проявляется сильней, чем при действиях в одиночку, и зависит от групповых ожиданий.', 1);