###Регистрация админа
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "name": "Сидоров Иван Иванович",
  "login": "admin1",
  "password": "admin1",
  "role": "ROLE_ADMIN",
  "email": "admin1@gmail.com",
  "birthday": "1998-06-16",
  "startWork": "2020-07-12",
  "workNumber": 1
}

###Регистрация обычного пользователя 1
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "name": "Иванов Иван Иванович",
  "login": "user1",
  "password": "user1",
  "email": "user1@gmail.com",
  "birthday": "1998-03-12",
  "startWork": "2022-03-12",
  "workNumber": 1
}

###Регистрация обычного пользователя 2
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "name": "Иванов Иван Иванович",
  "login": "user2",
  "password": "user2",
  "role": "ROLE_USER",
  "email": "user2@gmail.com",
  "birthday": "1996-05-23",
  "startWork": "2021-06-14",
  "workNumber": 1
}

###Регистрация обычного пользователя 3
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "name": "Иванов Иван Иванович",
  "login": "user3",
  "password": "user3",
  "email": "user3@gmail.com",
  "birthday": "1993-03-12",
  "startWork": "2013-03-12",
  "workNumber": 2
}