### Получение всех тестов системы
GET http://localhost:8080/api/v1/test-system/tests
Authorization: Bearer {{jwt}}

### Получение теста по id, связанных вопросов и вариантов ответов к ним
GET http://localhost:8080/api/v1/test-system/test/7
Authorization: Bearer {{jwt}}

### Получение вопроса по id вопроса и ответов к нему
GET http://localhost:8080/api/v1/test-system/question/1
Authorization: Bearer {{jwt}}

### Сохранение результата теста для пользователя
POST http://localhost:8080/api/v1/test-system/create/result
Content-Type: application/json
Authorization: Bearer {{jwt-admin}}

{
  "score": -5,
  "testId": 1,
  "userId": 3
}

### Получение критерия оценивания за тест по баллам, которые набрал за тест пользователь
GET http://localhost:8080/api/v1/test-system/assessment/1/-20
Authorization: Bearer {{jwt}}

### Принятие результата теста или нет
GET http://localhost:8080/api/v1/test-system/accept/result/10/true
Authorization: Bearer {{jwt}}

### Сохранение ответов пользователя на вопросы теста
POST http://localhost:8080/api/v1/test-system/create/answers
Content-Type: application/json
Authorization: Bearer {{jwt}}

[
  {
    "resultId": 7,
    "optionId": 7
  },
  {
    "resultId": 7,
    "optionId": 8
  }
]

### Получение ответов на тест для пользователя(по resultId)
GET http://localhost:8080/api/v1/test-system/answers/result/7
Content-Type: application/json
Authorization: Bearer {{jwt}}