GET http://localhost:8080/api/v1/test-system/assessment/1/-20
Authorization: Bearer {{jwt}}

<> 2024-05-11T000806.200.json
<> 2024-05-11T000734.200.json

###
GET http://localhost:8080/api/v1/test-system/tests
Authorization: Bearer {{jwt}}

<> 2024-05-11T001046.200.json

###
GET http://localhost:8080/api/v1/test-system/test/1
Authorization: Bearer {{jwt}}

<> 2024-05-11T001107.200.json

###
POST http://localhost:8080/api/v1/test-system/create/result
Content-Type: application/json
Authorization: Bearer {{jwt-admin}}

{
  "score": -5,
  "testId": 1,
  "userId": 3
}

###
GET http://localhost:8080/api/v1/user/2/results
Authorization: Bearer {{jwt-admin}}

###
POST http://localhost:8080/api/v1/test-system/create/answers
Content-Type: application/json
Authorization: Bearer {{jwt}}

[
  {
    "resultId": 7,
    "optionId": 7
  },
  {
    "resultId": 7,
    "optionId": 8
  }
]

###
GET http://localhost:8080/api/v1/test-system/answers/result/7
Content-Type: application/json
Authorization: Bearer {{jwt}}